services:
  frontend:
    build:
      context: ./pwa
    ports:
      - "8001:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped
